
services:
  auto-archiver:
  # point to the local dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-archiver
    volumes:
      - ./secrets:/app/secrets
      - ./local_archive:/app/local_archive
    command: --config secrets/orchestration.yaml
