[tool.poetry]
name = "auto-archiver"
# TODO Add check for consistent versioning
version = "0.13.0"
description = "Automatically archive links to videos, images, and social media content from Google Sheets (and more)."
authors = ["Bellingcat <info@bellingcat.com>"]
license = "MIT"
readme = "README.md"
keywords = ["archive", "oosi", "osint", "scraping"]
homepage = "https://github.com/bellingcat/auto-archiver"
repository = "https://github.com/bellingcat/auto-archiver"
documentation = "https://github.com/bellingcat/auto-archiver"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
packages = [
    { include = "auto_archiver", from = "src" }
]
# Mimicing setup.cfg
#packages = [
#    {include = "auto_archiver*", exclude = [
#        "examples*",
#        ".eggs*",
#        "build*",
#        "secrets*",
#        "tmp*",
#        "docs*",
#        "src.tests*"
#    ]}
#]

[tool.poetry.dependencies]
python = "~3.10"
gspread = "*"
argparse = "*"
beautifulsoup4 = "*"
tiktok-downloader = "*"
bs4 = "*"
loguru = "*"
ffmpeg-python = "*"
selenium = "*"
snscrape = "*"
telethon = "*"
google-api-python-client = "*"
google-auth-httplib2 = "*"
google-auth-oauthlib = "*"
oauth2client = "*"
pdqhash = "*"
pillow = "*"
python-slugify = "*"
pyyaml = "*"
dateparser = "*"
python-twitter-v2 = "*"
instaloader = "*"
tqdm = "*"
jinja2 = "*"
pyOpenSSL = "^23.0.0"
cryptography = "^41.0.0"
boto3 = "^1.28.0"
dataclasses-json = "*"
yt-dlp = "2024.09.27"
vk-url-scraper = "*"
requests = {extras = ["socks"], version = "*"}
numpy = "1.26.4"
warcio = "*"
jsonlines = "*"
pysubs2 = "*"
minify-html = "*"
retrying = "*"
tsp-client = "*"
certvalidator = "*"

[tool.poetry.dev-dependencies]
autopep8 = "*"

[tool.poetry.scripts]
auto-archiver = "auto_archiver.__main__:main"

#[tool.poetry.extras]
# Mimicing setup.cfg
# pdf = ["ReportLab>=1.2", "RXP"]
# rest = ["docutils>=0.3", "pack==1.1", "pack==1.3"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
