name: Core Tests

on:
  push:
    branches: [ main ]
    paths:
      - src/**
  pull_request:
    paths:
      - src/**

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Package (Local)
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run Core Tests
        run: |
          pytest -m "not download"
