name: Tests

on:
  push:
    branches: [ main, staging ]
    paths:
      - src/**
  pull_request:
    branches: [ main, staging ]
    paths:
      - src/**

jobs:
  test_back:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Package (Local)
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_EXAMPLE: "example env value - if we will use it (?)"
          directory: ./
      - name: Run Tests
        run: |
          pytest
